# Generated by Django 5.1.1 on 2024-10-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('identificacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=10)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('correo_electronico', models.EmailField(max_length=255, unique=True)),
                ('grado', models.CharField(max_length=50)),
            ],
        ),
    ]
