# Generated by Django 5.1.1 on 2024-10-09 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_curso_horario_alter_curso_dias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='cantidad_notas',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad de notas que se deben registrar para cada estudiante en este curso.'),
        ),
    ]
